import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AddressBar } from "@/components/ui/address-bar";
import { RouteChangesProvider } from 'nextjs-router-events';
import { LoadingPlaceholder } from "@/components/ui/loading-placeholder";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SHEMS - UI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen dark:bg-black">
          <RouteChangesProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <AddressBar />
                <div className="p-4 relative">
                  <LoadingPlaceholder>
                    {children}
                  </LoadingPlaceholder>
                  <Toaster />
                </div>
              </SidebarInset>
            </SidebarProvider>
          </RouteChangesProvider>
        </div>
      </body>
    </html>
  );
}
