import Base from "./base";

/**
 * Remote Power Storage Model
 *
 * The excess power generated by the house is stored in the remote(community) power storage
 */
export default class RmtStor extends Base {
	houseId: bigint;
	housePowerGenerateId: bigint;
	powerAmount: number;
	storageTime: Date;

	constructor(
		id: bigint,
		houseId: bigint,
		housePowerGenerateId: bigint,
		powerAmount: number,
		storageTime: Date,
		simulationTime: string,
	) {
		super(id, simulationTime);
		this.houseId = houseId;
		this.housePowerGenerateId = housePowerGenerateId;
		this.powerAmount = powerAmount;
		this.storageTime = storageTime;
	}
}